### ISSUE TITLE
Status of project

### ISSUE THREAD

**Issue by johnvanham** [Kerrialn/oauth2-example-project#1]
Hello,

I've been struggling with the lack of documentation on https://github.com/thephpleague/oauth2-server-bundle and reading through the issues (both open and closed) found your questions on https://github.com/thephpleague/oauth2-server-bundle/issues/61 and then this project.

I just wondered if this project is a fully working example or whether you had any issues with it still?

I'm really surprised at the lack of nicely documented oAuth2 libraries that are compatible with Symfony 5.3+

If you do still have any issues what are they and perhaps we can work them out together - I have a basic API that requires oAuth for 3rd party platforms and it needs to be production ready quickly, so am hoping your code will help me piece it together!

**Comment by johnvanham** [comment]
I've now got this working and have sent a PR with the changes I made: https://github.com/Kerrialn/oauth2-example-project/pull/2

**Comment by Kerrialn** [comment]
Hello, my apologies for the late response, just saw this. I have merged your pull request. 

this project is still active and I will maintain it as I too need a basic API skeleton implements oAuth for 3rd party applications, I too am frustrated with the lack of documentation. 

I'll close this is issue as I believe it's resolved.
